"use client";

import React, { useState } from "react";
import { useTheme } from "@/context/ThemeContext";

interface ArtifactExporterProps {
  taskTitle: string;
  domain: string;
  codeSnippet?: string;
  summaryText?: string;
  bookedDetails?: string;
}

export const ArtifactExporter: React.FC<ArtifactExporterProps> = ({
  taskTitle,
  domain,
  codeSnippet,
  summaryText,
  bookedDetails,
}) => {
  const { theme } = useTheme();
  const isDark = theme === "dark";
  const [copied, setCopied] = useState(false);

  const handleCopyCode = () => {
    const textToCopy = codeSnippet || summaryText || taskTitle;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPythonFile = () => {
    const code = codeSnippet || `# ${taskTitle}\nprint("Executed Orcheon Python Task")\n`;
    const blob = new Blob([code], { type: "text/x-python;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `orcheon_${domain}_task.py`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownloadICSFile = () => {
    const icsData = [
      "BEGIN:VCALENDAR",
      "VERSION:2.0",
      "PRODID:-//Orcheon Autonomous Platform//EN",
      "BEGIN:VEVENT",
      `SUMMARY:${taskTitle}`,
      `DESCRIPTION:${summaryText || "Scheduled via Orcheon Agentic Assistant"}`,
      "DTSTART:20260817T100000Z",
      "DTEND:20260817T110000Z",
      "END:VEVENT",
      "END:VCALENDAR",
    ].join("\r\n");

    const blob = new Blob([icsData], { type: "text/calendar;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", "orcheon_event.ics");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownloadMarkdownItinerary = () => {
    const mdContent = [
      `# Orcheon Travel Itinerary & Receipt`,
      `**Task**: ${taskTitle}`,
      `**Details**: ${summaryText || ""}`,
      `**ACP Booking Token**: acp_spt_4892_01`,
      `**Booked Reservations**: ${bookedDetails || "Air France AF224 & Grand Hotel Paris"}`,
      `---`,
      `Generated by Orcheon Autonomous Multi-Agent Platform`,
    ].join("\n\n");

    const blob = new Blob([mdContent], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", "orcheon_travel_itinerary.md");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: 10,
        marginTop: 14,
        paddingTop: 12,
        borderTop: isDark ? "1px solid #334155" : "1px solid #E2E8F0",
        fontFamily: "var(--font-sans), sans-serif",
      }}
    >
      <span style={{ fontSize: 11, fontWeight: 700, color: isDark ? "#94A3B8" : "#64748B", textTransform: "uppercase" }}>
        Export Artifact:
      </span>

      {domain === "coding" && (
        <>
          <button
            onClick={handleDownloadPythonFile}
            style={{
              background: "rgba(99,102,241,0.12)",
              color: "#6366F1",
              border: "1px solid rgba(99,102,241,0.3)",
              borderRadius: 10,
              padding: "4px 10px",
              fontSize: 11,
              fontWeight: 700,
              cursor: "pointer",
            }}
          >
            📥 Download .py Script
          </button>
          <button
            onClick={handleCopyCode}
            style={{
              background: isDark ? "#334155" : "#F1F5F9",
              color: isDark ? "#CBD5E1" : "#475569",
              border: "none",
              borderRadius: 10,
              padding: "4px 10px",
              fontSize: 11,
              fontWeight: 700,
              cursor: "pointer",
            }}
          >
            {copied ? "✓ Copied!" : "📋 Copy Code"}
          </button>
        </>
      )}

      {domain === "scheduling" && (
        <button
          onClick={handleDownloadICSFile}
          style={{
            background: "rgba(16,185,129,0.12)",
            color: "#10B981",
            border: "1px solid rgba(16,185,129,0.3)",
            borderRadius: 10,
            padding: "4px 10px",
            fontSize: 11,
            fontWeight: 700,
            cursor: "pointer",
          }}
        >
          📅 Export .ics Calendar File
        </button>
      )}

      {domain === "trip" && (
        <button
          onClick={handleDownloadMarkdownItinerary}
          style={{
            background: "rgba(59,130,246,0.12)",
            color: "#3B82F6",
            border: "1px solid rgba(59,130,246,0.3)",
            borderRadius: 10,
            padding: "4px 10px",
            fontSize: 11,
            fontWeight: 700,
            cursor: "pointer",
          }}
        >
          📄 Export Markdown Itinerary
        </button>
      )}
    </div>
  );
};
